package com.mossle.user.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.mossle.auth.persistence.domain.Shift;
import com.mossle.dict.persistence.domain.DictInfo;

/**
 * person_contract_company 合同单位管理.
 * 
 * @author chengze 20181206
 */
@Entity
@Table(name = "person_contract_company")
public class PersonContractCompanyManage implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 合同单位名称. */
    private String contractCompanyName;

    /** 单位邮箱. */
    private String companyEmail;
    
    /** 租户id. */
    private String tenantId;

    /** 备注. */
    private String remark;

    /** 是否启用. */
    private String isenable;
    //ckx 2019/2/1
    /** smtp服务器. */
    private DictInfo smtpServer;
    /** pop服务器. */
    private DictInfo popServer;
    
    /** @return 外键，DICT_INFO. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "smtp_dict_type_id")
	public DictInfo getSmtpServer() {
		return smtpServer;
	}

	public void setSmtpServer(DictInfo smtpServer) {
		this.smtpServer = smtpServer;
	}
	/** @return 外键，DICT_INFO. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "pop_dict_type_id")
	public DictInfo getPopServer() {
		return popServer;
	}

	public void setPopServer(DictInfo popServer) {
		this.popServer = popServer;
	}

	public PersonContractCompanyManage() {
    }

    public PersonContractCompanyManage(Long id) {
        this.id = id;
    }

    public PersonContractCompanyManage(Long id, String contractCompanyName, String companyEmail, String remark){
        this.id = id;
        this.contractCompanyName = contractCompanyName;
        this.companyEmail = companyEmail;
        this.remark = remark;
    }

    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name = "contract_company_name" )
	public String getContractCompanyName() {
		return contractCompanyName;
	}

	public void setContractCompanyName(String contractCompanyName) {
		this.contractCompanyName =contractCompanyName ;
	}

	
	@Column(name = "company_email")
	public String getCompanyEmail() {
		return companyEmail;
	}

	public void setCompanyEmail(String companyEmail) {
		this.companyEmail = companyEmail;
	}

	
	@Column(name = "tenant_id")
	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	@Column(name = "remark")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "isenable")
	public String getIsenable() {
		return isenable;
	}

	public void setIsenable(String isenable) {
		this.isenable = isenable;
	}

    
	
}
