package com.mossle.user.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonInfo 个人信息.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "oa_bpm_rosterlog")
public class RosterLog implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 受理单编号. */
    private String code;

    /** 操作人员id. */
    private String operationID;

    /**被修改的员工编号. */
    private String employeeNo;

    /**被修改的字段名. */
    private String updateColumn;
    
    /**被修改的字段的中文名称. */
    private String updateColumnName;
   
    /** 修改之前的内容. */
    private String contentBefore;
    
    /** 修改后的新内容. */
    private String contentNew;

    /** 修改时间. */
    private Date updateTime;
    
    /** 0：表示流程审核成功；1：表示流程审核失败或审核中. */
    private String isapproval;


    
	public RosterLog() {
    }

    public RosterLog(Long id) {
        this.id = id;
    }

    
    

	/** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 唯一标识. */
    @Column(name = "CODE", length = 200)
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            唯一标识.
     */
    public void setCode(String code) {
        this.code = code;
    }
    
    
    /** 操作人员id. */
    @Column(name = "OPERATION_ID")
    public String getOperationID() {
		return operationID;
	}

	public void setOperationID(String operationID) {
		this.operationID = operationID;
	}

	
	 /** 被修改的字段名. */
    @Column(name = "UPDATE_COLUMN")
	public String getUpdateColumn() {
		return updateColumn;
	}

	public void setUpdateColumn(String updateColumn) {
		this.updateColumn = updateColumn;
	}

	
	 /** 被修改的字段的中文名称. */
	 @Column(name = "UPDATE_COLUMN_NAME")
	 public String getUpdateColumnName() {
		return updateColumnName;
	}

	public void setUpdateColumnName(String updateColumnName) {
		this.updateColumnName = updateColumnName;
	}

	/** 操作人员id. */
    @Column(name = "CONTENT_BEFORE")
	public String getContentBefore() {
		return contentBefore;
	}

	public void setContentBefore(String contentBefore) {
		this.contentBefore = contentBefore;
	}

	
	 /** 操作人员id. */
    @Column(name = "CONTENT_NEW")
	public String getContentNew() {
		return contentNew;
	}

	public void setContentNew(String contentNew) {
		this.contentNew = contentNew;
	}

	
	 /** 操作人员id. */
    @Column(name = "UPDATE_TIME")
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	
	/**被修改的员工编号. */
    @Column(name = "EMPLOYEENO")
	public String getEmployeeNo() {
		return employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

		
	
	/**0：表示流程审核成功；1：表示流程审核失败或审核中. */
    @Column(name = "ISAPPROVAL")
	public String getIsapproval() {
		return isapproval;
	}

	public void setIsapproval(String isapproval) {
		this.isapproval = isapproval;
	}

	
	
}
