package com.mossle.user.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PersonInfo 个人信息.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "oa_bpm_update_person")
public class UpdatePerson implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 修改花名册实体类的内容. */
    private String jsonContent;

    /** 1：流程审核同意   0：流程审核不同意. */
    private String isApproval;

    /** 受理单编号. */
    private String applyCode;
 
    /**参数. */
    private String updateParameters;
    
    /**参数. */
    private String employeeNo;
    
    /**类型：1 是 person表的 ；2 是 岗位信息. */
    private String typeID;
    
    
	public UpdatePerson() {
    }

    public UpdatePerson(Long id) {
        this.id = id;
    }


    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /** @return 修改花名册实体类的内容. */
    @Column(name = "JSONCONTENT")
    public String getJsonContent() {
		return jsonContent;
	}

	public void setJsonContent(String jsonContent) {
		this.jsonContent = jsonContent;
	}

	
	/** @return 受理单编号. */
    @Column(name = "APPLYCODE")
	public String getApplyCode() {
		return applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	/** 1：流程审核同意   0：流程审核不同意. */
    @Column(name = "ISAPPROVAL")
	public String getIsApproval() {
		return isApproval;
	}

	public void setIsApproval(String isApproval) {
		this.isApproval = isApproval;
	}

	/** 参数. */
    @Column(name = "PARAMETERS")
	public String getUpdateParameters() {
		return updateParameters;
	}

	public void setUpdateParameters(String updateParameters) {
		this.updateParameters = updateParameters;
	}

	/** 参数. */
    @Column(name = "EMPLOYEE_NO")
	public String getEmployeeNo() {
		return employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	
	/** 类型：1 是 person表的 ；2 是 岗位信息. */
    @Column(name = "TYPEID")
	public String getTypeID() {
		return typeID;
	}

	public void setTypeID(String typeID) {
		this.typeID = typeID;
	}

	

}
