package com.mossle.party.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * 组织机构变更日志表.
 * 
 * @author cz 20181016 
 */
@Entity
@Table(name = "oa_ba_orgLog")
public class OrgLogEntity implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 组织机构id. */
    private Long orgID;

    /** 操作人. */
    private Long operationID;
    
    /** 操作时间. */
    private Date operationTime;
    
    /** 修改内容. */
    private String modifyContent;
    
    /** 流程的受理单编号. */
    private String applyCode;

    /** 备注. */
    private String remark;


    

    public OrgLogEntity() {
    }

    public OrgLogEntity(Long id) {
        this.id = id;
    }

    public OrgLogEntity(Long id,  Long operationID, Date operationTime,
            String modifyContent, String applyCode, String remark) {
        this.id = id;
        this.operationID = operationID;
        this.operationTime = operationTime;
        this.modifyContent = modifyContent;
        this.applyCode = applyCode;
        this.remark = remark;
    }

    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

 
    @Column(name = "orgID", length = 100)
    public Long getOrgID() {
		return orgID;
	}

	public void setOrgID(Long orgID) {
		this.orgID = orgID;
	}

	@Column(name = "operationID", length = 100)
	public Long getOperationID() {
		return operationID;
	}

	public void setOperationID(Long operationID) {
		this.operationID = operationID;
	}

	
	
	@Column(name = "operationTime", length = 100)
	public Date getOperationTime() {
		return operationTime;
	}

	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	
	
	@Column(name = "modifyContent", length = 100)
	public String getModifyContent() {
		return modifyContent;
	}

	public void setModifyContent(String modifyContent) {
		this.modifyContent = modifyContent;
	}

	
	
	@Column(name = "applyCode", length = 100)
	public String getApplyCode() {
		return applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	
	
	@Column(name = "remark", length = 100)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

  

}
