package com.mossle.api.user;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;

/**
 * PersonInfo 个人信息.
 * 
 */

public class PersonInfoDTO {
	
    /** 主键. */
    private Long id;

    /** 唯一标识. */
    private String code;

    /** 账号. */
    private String userName;
    
    /** 真实姓名. */
    private String realName;
    
    /** 密码. */
    private String password;

    /** 确认密码. */
    private String confirmPassword;
    
    /** 姓氏. */
    private String familyName;

    /** 名字. */
    private String givenName;

    /** 全名. */
    private String fullName;

    /** 手机. */
    private String cellphone;

    /** 座机. */
    private String telephone;

    /** 邮箱. */
    private String email;
    
    /** 紧急联系人及电话  **/
    private String fax;
    
    /** QQ **/
    private String qq;
    
    /** 微信号  **/
    private String wxNo;

    /** 即时通讯. */
    private String im;

    /** 国家. */
    private String country;

    /** 省. */
    private String province;

    /** 市. */
    private String city;

    /** 办公楼. */
    private String building;

    /** 楼层. */
    private String floor;

    /** 工位. */
    private String seat;

    /** 工号-部门缩写. */
    private String employeeNoDepart;
    
    /** 工号-数字部分. */
    private String employeeNoNum;

    /** 工号-完整拼接. */
    private String employeeNo;
    
    /** 员工类型. */
    private String employeeType;

    /** 工卡. */
    private String card;

    /** 公司编码. */
    private String companyCode;

    /** 公司名称. */
    private String companyName;

    /** 部门编码. */
    private String departmentCode;

    /** 部门名称. */
    private String departmentName;

    /** 职位编码. */
    private String positionCode;

    /** 职位名称. */
    private String positionName;
    
    /** 岗位编码. */
    private String postId;
    
    /** 岗位名称. */
    private String postName;
    
    

    /** 性别. */
    private String gender;

    /** 生日. */
    private Date birthday;

    /** 证件类型. */
    private String idCardType;

    /** 证件编号. */
    private String idCardValue;

    /** 国籍. */
    private String nationality;

    /** 星座. */
    private String star;

    /** 血型. */
    private String blood;

    /** 衣服大小. */
    private String clothSize;

    /** 租户. */
    private String tenantId;

    /** 联系地址. */
    private String address;
    
    /** 停用启用标识. */
    private String stopFlag;
    
    /** 离职在职标识. */
    private int quitFlag;

    /** 机构Id,对于机构中的人员. */
    private Long partyId;
    
    /** 添加时间. */
    private String addTime;
    
    /** 是否兼职. */
    private String jobStatus;
    
    /** 离职日期. */
    private String quitTime;

	/** 联系电话公开方式 **/
	private String secret;

	/** 上级机构Id **/
	private String parentId;

	  /** 曾用名. */
    private String nameBefore;

    //级别
    private String level ;
    
    //籍贯
    private  String nativePlace;
    
    //户口所在地
    private  String registeredResidence;
    
    //户籍类型
    private  String householdRegisterType;
    
    //政治面貌
    private  String politicalOutlook;
    
    //民族
    private  String nation;
    
    //专业
    private  String major;
    
    //职称
    private  String title;
    
    //学位
    private  String academicDegree;
    //技能特长
    private  String skillSpecialty;
    //用工类型
    private  String laborType;
    //进入方式
    private  String entryMode;
    //学历
    private  String education;
    //婚否
    private  String marriage;
    //生育情况
    private  String fertilityCondition;
    //入职时间
    private  String entryTime;
    //合同到期时间
    private  String contractExpirationTime;
    //合同有效期
    private  String contractDeadline;
    
    //合同单位
    private  String contractCompany;
    
    //保险情况
    private  String insurance;
    
    //资料情况
    private  String document;
    
    //身份证号
    private  String identityID;
    
    //备注
    private  String remark;
    
    //1：流程审核同意   0：流程审核不同意
    private  String isApproval ;
	

    //家庭成员1
    private  String family_1;
    //家庭成员2
    private  String family_2;
    
    //教育经历1
    private  String educational_experience_1;
    //教育经历2
    private  String educational_experience_2;
    //教育经历3
    private  String educational_experience_3;
    
    //工作经历1
    private  String work_experience_1;
    //工作经历2
    private  String work_experience_2;
    
    //实际离职日期
    private String leaveDate;
    
	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getConfirmPassword() {
		return confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public String getFamilyName() {
		return familyName;
	}

	public void setFamilyName(String familyName) {
		this.familyName = familyName;
	}

	public String getGivenName() {
		return givenName;
	}

	public void setGivenName(String givenName) {
		this.givenName = givenName;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getCellphone() {
		return cellphone;
	}

	public void setCellphone(String cellphone) {
		this.cellphone = cellphone;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	

    public String getFax() {
		return fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}
	
	public String getQq() {
		return qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getWxNo() {
		return wxNo;
	}
	
	public void setWxNo(String wxNo) {
		this.wxNo = wxNo;
	}
	
	
	public String getIm() {
		return im;
	}

	public void setIm(String im) {
		this.im = im;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getBuilding() {
		return building;
	}

	public void setBuilding(String building) {
		this.building = building;
	}

	public String getFloor() {
		return floor;
	}

	public void setFloor(String floor) {
		this.floor = floor;
	}

	public String getSeat() {
		return seat;
	}

	public void setSeat(String seat) {
		this.seat = seat;
	}

	 /** @return 工号-部门缩写. */
    public String getEmployeeNoDepart() {
		return employeeNoDepart;
	}

	public void setEmployeeNoDepart(String employeeNoDepart) {
		this.employeeNoDepart = employeeNoDepart;
	}

	  /** 工号-数字部分. */
	public String getEmployeeNoNum() {
		return employeeNoNum;
	}

	public void setEmployeeNoNum(String employeeNoNum) {
		this.employeeNoNum = employeeNoNum;
	}

	
	  /** 工号-完整拼接. */
	public String getEmployeeNo() {
		return employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	

	public String getEmployeeType() {
		return employeeType;
	}

	public void setEmployeeType(String employeeType) {
		this.employeeType = employeeType;
	}

	public String getCard() {
		return card;
	}

	public void setCard(String card) {
		this.card = card;
	}

	public String getCompanyCode() {
		return companyCode;
	}

	public void setCompanyCode(String companyCode) {
		this.companyCode = companyCode;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getDepartmentCode() {
		return departmentCode;
	}

	public void setDepartmentCode(String departmentCode) {
		this.departmentCode = departmentCode;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getPositionCode() {
		return positionCode;
	}

	public void setPositionCode(String positionCode) {
		this.positionCode = positionCode;
	}

	public String getPositionName() {
		return positionName;
	}

	public void setPositionName(String positionName) {
		this.positionName = positionName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBirthday() {
		return birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getIdCardType() {
		return idCardType;
	}

	public void setIdCardType(String idCardType) {
		this.idCardType = idCardType;
	}

	public String getIdCardValue() {
		return idCardValue;
	}

	public void setIdCardValue(String idCardValue) {
		this.idCardValue = idCardValue;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public String getStar() {
		return star;
	}

	public void setStar(String star) {
		this.star = star;
	}

	public String getBlood() {
		return blood;
	}

	public void setBlood(String blood) {
		this.blood = blood;
	}

	public String getClothSize() {
		return clothSize;
	}

	public void setClothSize(String clothSize) {
		this.clothSize = clothSize;
	}

	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStopFlag() {
		return stopFlag;
	}

	public void setStopFlag(String stopFlag) {
		this.stopFlag = stopFlag;
	}

	public int getQuitFlag() {
		return quitFlag;
	}

	public void setQuitFlag(int quitFlag) {
		this.quitFlag = quitFlag;
	}

	public Long getPartyId() {
		return partyId;
	}

	public void setPartyId(Long partyId) {
		this.partyId = partyId;
	}

	public String getAddTime() {
		return addTime;
	}

	public void setAddTime(String addTime) {
		this.addTime = addTime;
	}

	public String getJobStatus() {
		return jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	public String getQuitTime() {
		return quitTime;
	}

	public void setQuitTime(String quitTime) {
		this.quitTime = quitTime;
	}

	public String getSecret() {
		return secret;
	}

	public void setSecret(String secret) {
		this.secret = secret;
	}

	public String getParentId() {
		return parentId;
	}

	public void setParentId(String parentId) {
		this.parentId = parentId;
	}
	
	

    /** @return 级别. */
	public String getLevel() {
		return level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	/** @return 籍贯. */
	public String getNativePlace() {
		return nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	/** @return 户口所在地. */
	public String getRegisteredResidence() {
		return registeredResidence;
	}

	public void setRegisteredResidence(String registeredResidence) {
		this.registeredResidence = registeredResidence;
	}

	/** @return 户籍类型. */
	public String getHouseholdRegisterType() {
		return householdRegisterType;
	}

	public void setHouseholdRegisterType(String householdRegisterType) {
		this.householdRegisterType = householdRegisterType;
	}

	/** @return 政治面貌. */
	public String getPoliticalOutlook() {
		return politicalOutlook;
	}

	public void setPoliticalOutlook(String politicalOutlook) {
		this.politicalOutlook = politicalOutlook;
	}

	/** @return 民族. */
	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	/** @return 专业. */
	public String getMajor() {
		return major;
	}

    /** @return 专业. */
	public void setMajor(String major) {
		this.major = major;
	}

	/** @return 学位. */
	public String getAcademicDegree() {
		return academicDegree;
	}

	public void setAcademicDegree(String academicDegree) {
		this.academicDegree = academicDegree;
	}

	/** @return 技能特长. */
	public String getSkillSpecialty() {
		return skillSpecialty;
	}

	public void setSkillSpecialty(String skillSpecialty) {
		this.skillSpecialty = skillSpecialty;
	}

	/** @return 用工类型. */
	public String getLaborType() {
		return laborType;
	}

	public void setLaborType(String laborType) {
		this.laborType = laborType;
	}

	/** @return 进入方式. */
	public String getEntryMode() {
		return entryMode;
	}

	public void setEntryMode(String entryMode) {
		this.entryMode = entryMode;
	}

	/** @return 学历. */
	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	/** @return 婚否. */
	public String getMarriage() {
		return marriage;
	}

	public void setMarriage(String marriage) {
		this.marriage = marriage;
	}

	/** @return 生育情况. */
	public String getFertilityCondition() {
		return fertilityCondition;
	}

	public void setFertilityCondition(String fertilityCondition) {
		this.fertilityCondition = fertilityCondition;
	}

	/** @return 入职时间. */
	public String getEntryTime() {
		return entryTime;
	}

	public void setEntryTime(String entryTime) {
		this.entryTime = entryTime;
	}

	/** @return 合同到期时间. */
	public String getContractExpirationTime() {
		return contractExpirationTime;
	}

	public void setContractExpirationTime(String contractExpirationTime) {
		this.contractExpirationTime = contractExpirationTime;
	}

	/** @return 合同有效期. */
	public String getContractDeadline() {
		return contractDeadline;
	}

	public void setContractDeadline(String contractDeadline) {
		this.contractDeadline = contractDeadline;
	}

	/** @return 合同单位. */
	public String getContractCompany() {
		return contractCompany;
	}

	public void setContractCompany(String contractCompany) {
		this.contractCompany = contractCompany;
	}

	/** @return 保险情况. */
	public String getInsurance() {
		return insurance;
	}

	public void setInsurance(String insurance) {
		this.insurance = insurance;
	}

	/** @return 资料情况. */
	public String getDocument() {
		return document;
	}

	public void setDocument(String document) {
		this.document = document;
	}

	/** @return 身份证号. */
	public String getIdentityID() {
		return identityID;
	}

	public void setIdentityID(String identityID) {
		this.identityID = identityID;
	}

	/** @return 备注. */
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/** @return 职称. */
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	
	/** @return 1：流程审核同意   0：流程审核不同意. */
	public String getIsApproval() {
		return isApproval;
	}

	public void setIsApproval(String isApproval) {
		this.isApproval = isApproval;
	}
	
	/** @return 曾用名. */
	public String getNameBefore() {
		return nameBefore;
	}

    /** @return 曾用名. */
	public void setNameBefore(String nameBefore) {
		this.nameBefore = nameBefore;
	}
	

	/** @return 家庭成员 1 . */
	public String getFamily_1() {
		return family_1;
	}

	public void setFamily_1(String family_1) {
		this.family_1 = family_1;
	}

	
	/** @return 家庭成员 2 . */
	public String getFamily_2() {
		return family_2;
	}

	public void setFamily_2(String family_2) {
		this.family_2 = family_2;
	}

	
	/** @return 教育经历1 . */
	public String getEducational_experience_1() {
		return educational_experience_1;
	}

	public void setEducational_experience_1(String educational_experience_1) {
		this.educational_experience_1 = educational_experience_1;
	}

	
	/** @return 教育经历2 . */
	public String getEducational_experience_2() {
		return educational_experience_2;
	}

	public void setEducational_experience_2(String educational_experience_2) {
		this.educational_experience_2 = educational_experience_2;
	}

	
	/** @return 教育经历3 . */
	public String getEducational_experience_3() {
		return educational_experience_3;
	}

	public void setEducational_experience_3(String educational_experience_3) {
		this.educational_experience_3 = educational_experience_3;
	}

	
	/** @return 工作经历1 . */
	public String getWork_experience_1() {
		return work_experience_1;
	}

	public void setWork_experience_1(String work_experience_1) {
		this.work_experience_1 = work_experience_1;
	}

	/** @return 工作经历2 . */
	public String getWork_experience_2() {
		return work_experience_2;
	}

	public void setWork_experience_2(String work_experience_2) {
		this.work_experience_2 = work_experience_2;
	}

	
	/** @return 岗位编码 . */
	public String getPostId() {
		return postId;
	}

	public void setPostId(String postId) {
		this.postId = postId;
	}

	/** @return  岗位名称 . */
	public String getPostName() {
		return postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	/** @return  真实姓名 . */
	public String getRealName() {
		return realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}
	
	/** @return  实际离职日期 */
	public String getLeaveDate() {
		return leaveDate;
	}

	public void setLeaveDate(String leaveDate) {
		this.leaveDate = leaveDate;
	}
	
	
	
}
