package com.mossle.api.user;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Id;

/**
 * PersonInfo 个人信息.
 * 
 */

public class RosterLogDTO {
	

    /** 主键. */
    private Long id;

    /** 受理单编号. */
    private String code;

    /** 操作人员id. */
    private String operationID;

    /**被修改的员工编号. */
    private String employeeNo;

    /**被修改的字段名. */
    private String updateColumn;
    
    /**被修改的字段的中文名称. */
    private String updateColumnName;

    /** 修改之前的内容. */
    private String contentBefore;
    
    /** 修改后的新内容. */
    private String contentNew;

    /** 修改时间. */
    private String updateTime;


    
	public RosterLogDTO() {
    }

    public RosterLogDTO(Long id) {
        this.id = id;
    }

    
    

	/** @return 主键. */
    @Id
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 唯一标识. */
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            唯一标识.
     */
    public void setCode(String code) {
        this.code = code;
    }
    
    
    /** 操作人员id. */
    public String getOperationID() {
		return operationID;
	}

	public void setOperationID(String operationID) {
		this.operationID = operationID;
	}

	
	 /** 操作人员id. */
	public String getUpdateColumn() {
		return updateColumn;
	}

	public void setUpdateColumn(String updateColumn) {
		this.updateColumn = updateColumn;
	}

	
	 /** 操作人员id. */
	public String getContentBefore() {
		return contentBefore;
	}

	public void setContentBefore(String contentBefore) {
		this.contentBefore = contentBefore;
	}

	
	 /** 操作人员id. */
	public String getContentNew() {
		return contentNew;
	}

	public void setContentNew(String contentNew) {
		this.contentNew = contentNew;
	}

	
	 /** 操作人员id. */
	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}
	
	/** 被修改的字段的中文名称. */
	 public String getUpdateColumnName() {
		return updateColumnName;
	}

	public void setUpdateColumnName(String updateColumnName) {
		this.updateColumnName = updateColumnName;
	}

	public String getEmployeeNo() {
		return employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}
	
	
}
