package com.mossle.operation.persistence.domain;


//Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/** 
 * @author  cz 
 * @version 2017年7月26日
 * 业务受理申请单 
 */
public class ApplyDTO extends CommonDTO implements java.io.Serializable {

    private static final long serialVersionUID = 0L;
    
    /** 主键. */
    private Long id;
    /** 受理单编号 */
    private String applyCode;
  
    /** 给谁申请- 经销商编号. */
    private String ucode;

    /** 申请内容. */
    private String applyContent;
    
    /** 申请人 流程发起人. */
    private Long userId;
    
    /** 流程实例Id. */
    private String PROCESS_INSTANCEID;
     /** 附件名称 */
    private String fileName;  
    /** 附件路径 */
    private String filePath;
    /** 姓名 */
    private String  userName  ;
    /** 福利级别 */
    private String  welfare  ;
    /** 级别 */
    private String  level  ;
    /** 所属体系 */
    private String  system  ;
    /** 销售人 */
    private String  varFather  ;
    /** 服务人 */
    private String  varRe  ;
    /** 注册时间 */
    private String  addTime  ;
    /** 申请业务类型 */
    private String  businessType  ;
    /** 业务细分 */
    private String  businessDetail  ;
    /** 电话 */
    private String  mobile  ;
    /** 地址 */
    private String  address  ;
    /** 业务级别 */
    private String  businessLevel  ;
    /** 所属大区 */
    private String  area  ;
    /** 业务标准（现场办理） */
    private String  businessStand1  ;
    /** 业务标准（非现场办理） */
    private String  businessStand2  ;
    /** 点位信息 */
    private String  treeInfo  ;
    /** 该条任务的创建时间 */
    private Date  createTime  ;
    /** 该条任务的调整后重新发起时间 */
    private Date  modifyTime  ;
    /** 提交次数 */
    private int submitTimes;
    /**用于导出*/
    private Date completeTime;
    /** 批示内容 */
    private String  comment ;
    public ApplyDTO() {
    }
    
    public ApplyDTO(Long id) {
        this.id = id;
    }
    
    public ApplyDTO(Long id,String ucode, String applyContent, String PROCESS_INSTANCEID,Long userid,String welfare) 
    {
    	this.id = id;
    	this.ucode = ucode;
    	this.applyContent = applyContent;
    	this.PROCESS_INSTANCEID = PROCESS_INSTANCEID;    	
        this.userId = userid;  
        this.welfare = welfare;
        
    }
    

	/** @return 主键. */
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /** @return 受理单编号. */
    public String getApplyCode() {
  		return applyCode;
  	}

  	public void setApplyCode(String applyCode) {
  		this.applyCode = applyCode;
  	}
    

    /** @return 经销商编号. */
   
    public String getUcode() {
        return this.ucode;
    }

    /**
     * @param content
     *            经销商编号.
     */
    public void setUcode(String ucode) {
        this.ucode = ucode;
    }    
    

    /** @return 申请内容. */
     public String getApplyContent() {
        return this.applyContent;
    }

    /**
     * @param content
     *            申请内容.
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent;
    }


    /** @return 申请人. */
    public Long getUserId() {
        return this.userId;
    }
    /**
     * @param id
     *            申请人.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    
	public String getProcessInstanceId() {
		return this.PROCESS_INSTANCEID;
	}


	public void setProcessInstanceId(String PROCESS_INSTANCEID) {
		this.PROCESS_INSTANCEID = PROCESS_INSTANCEID;
	}
	
	

    /** @return 附件名称. */
    public String getFileName() {
        return this.fileName;
    }
    /**
     * @param 
     *            附件名称.
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    
    
    /** @return 附件路径. */
    public String getFilePath() {
        return this.filePath;
    }
    /**
     * @param 
     *            附件路径.
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    
    /** @return 姓名. */
    public String getUserName() {
        return this.userName;
    }

    /**
     * @param 姓名.
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    /** @return 福利级别. */
    public String getWelfare() {
        return this.welfare;
    }

    /**
     * @param 
     *            福利级别.
     */
    public void setWelfare(String welfare) {
        this.welfare = welfare;
    }
    
    /** @return 级别. */
    public String getLevel() {
        return this.level;
    }

    /**
     * @param 
     *            级别.
     */
    public void setLevel(String level) {
        this.level = level;
    }
    
    /** @return 所属体系 */
    public String getSystem() {
        return this.system;
    }

    /**
     * @param 所属体系
     */
    public void setSystem(String system) {
        this.system = system;
    }
    
    
    /** @return 销售人 */
    public String getVarFather() {
        return this.varFather;
    }

    /**
     * @param 销售人
     */
    public void setVarFather(String varFather) {
        this.varFather = varFather;
    }
    
    /** @return 服务人 */
    public String getVarRe() {
        return this.varRe;
    }

    /**
     * @param 服务人
     */
    public void setVarRe(String varRe) {
        this.varRe = varRe;
    }
    
    /** @return 注册时间 */
    public String getAddTime() {
        return this.addTime;
    }

    /**
     * @param 注册时间
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }
    
    
    /** @return 申请业务类型 */
    public String getBusinessType() {
        return this.businessType;
    }

    /**
     * @param 申请业务类型
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }
    
    /** @return 业务细分 */
    public String getBusinessDetail() {
        return this.businessDetail;
    }

    /**
     * @param 业务细分
     */
    public void setBusinessDetail(String businessDetail) {
        this.businessDetail = businessDetail;
    }
    
    /** @return 电话 */
    public String getMobile() {
        return this.mobile;
    }

    /**
     * @param 电话
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    /** @return 地址 */
    public String getAddress() {
        return this.address;
    }

    /**
     * @param 地址
     */
    public void setAddress(String address) {
        this.address = address;
    }
    
    /** @return 业务级别 */
    public String getBusinessLevel() {
        return this.businessLevel;
    }

    /**
     * @param 业务级别
     */
    public void setBusinessLevel(String businessLevel) {
        this.businessLevel = businessLevel;
    }
    
    /** @return 所属大区 */
    public String getArea() {
        return this.area;
    }

    /**
     * @param 所属大区
     */
    public void setArea(String area) {
        this.area = area;
    }
    
    /** @return 业务标准（现场办理） */
    public String getBusinessStand1() {
        return this.businessStand1;
    }

    /**
     * @param 业务标准（现场办理）
     */
    public void setBusinessStand1(String businessStand1) {
        this.businessStand1 = businessStand1;
    }
    
    
    /** @return 业务标准（非现场办理） */
    public String getBusinessStand2() {
        return this.businessStand2;
    }

    /**
     * @param 业务标准（非现场办理）
     */
    public void setBusinessStand2(String businessStand2) {
        this.businessStand2 = businessStand2;
    }
    
    
    /** @return 业务标准（非现场办理） */
    public String getTreeInfo() {
        return this.treeInfo;
    }

    /**
     * @param 业务标准（非现场办理）
     */
    public void setTreeInfo(String treeInfo) {
        this.treeInfo = treeInfo;
    }
    

    /** @return  */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    /** @return . */
    public Date getModifyTime() {
        return this.modifyTime;
    }

    /**
     * @param content
     *            .
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }   
    
    /**
     * @param 提交次数
     *            .
     */
    public int getSubmitTimes() {
		return submitTimes;
	}

	public void setSubmitTimes(int submitTimes) {
		this.submitTimes = submitTimes;
	}

	public Date getCompleteTime() {
		return completeTime;
	}

	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
    
}
