package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * 
 * 冻结/解冻实体
 * @author sjx
 */
@Entity
@Table(name = "ENTITY_FREEZE")
public class Freeze implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 编号. */
    private String ucode;

    /** 姓名. */
    private String name;

    /** 联系方式. */
    private String contact;

    /** 销售级别. */
    private String salesLevel;

    /** 福利级别. */
    private String welfareLevel;

    /** 激活状态. */
    private String activationState;
    
    /** 所属体系. */
    private String system;
    
    /** 上属董事. */
    private String aboveBoard;
    
    /** 冻结状态. */
    private String frozenState;
    
    /** 所属区域. */
    private String area;
    
    /** 董事姓名. */
    private String director;
    
    /** 联系方式（董事）. */
    private String directorContact;
    
    /** 所属分公司. */
    private String branchOffice;
    
    /** 身份证号. */
    private String idNumber;
    
    /**申请受理事项*/
    private String applyMatter;
    
    /**申请内容*/
    private String applyContent;
    
    /** 附件名 */
    private String enclosure;
    
    /** 附件路径 */
    private String path;
    
    /** 申请人. */
    private Long userId;
    
    /** 流程实例Id. */
    private String processInstanceId;
    
    
    public Freeze() {
    }

    public Freeze(Long id) {
        this.id = id;
    }

    
    public Freeze(Long id, String ucode, String name,String contact,String salesLevel,String welfareLevel, String activationState, String system,String aboveBoard,String frozenState,
    		 String area,String director,String directorContact,String branchOffice,String idNumber,String applyMatter,String applyContent,String enclosure,String path,
    		Long userId, String processInstanceId) {
        this.id = id;
        this.ucode = ucode;
        this.name = name;
        this.contact = contact;
        this.salesLevel = salesLevel;
        this.welfareLevel = welfareLevel;
        this.activationState = activationState;
        this.system = system;
        this.aboveBoard = aboveBoard;
        this.frozenState = frozenState;
        this.area = area;
        this.director = director;
        this.directorContact = directorContact;
        this.branchOffice = branchOffice;
        this.idNumber = idNumber;
        this.applyMatter = applyMatter;
        this.applyContent = applyContent;
        this.enclosure = enclosure;
        this.path = path;
        this.userId = userId;
        this.processInstanceId = processInstanceId;
    }

    

	/** @return 主键. */
    @Id
    @Column(name = "id")
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }


    /** @return 编号. */
    @Column(name = "ucode")
    public String getUcode() {
        return this.ucode;
    }

    /**
     * @param number
     * 编号.
     */
    public void setUcode(String ucode) {
        this.ucode = ucode;
    }
    
    /** @return 姓名. */
    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     * 姓名.
     */
    public void setName(String name) {
        this.name = name;
    }
    
    /** @return 联系方式. */
    @Column(name = "contact")
    public String getContact() {
        return this.contact;
    }

    /**
     * @param contact
     * 联系方式.
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /** @return 销售级别. */
    @Column(name = "sales_level")
    public String getSalesLevel() {
        return this.salesLevel;
    }

    /**
     * @param salesLevel
     * 销售级别.
     */
    public void setSalesLevel(String salesLevel) {
        this.salesLevel = salesLevel;
    }

    /** @return 福利级别. */
    @Column(name = "welfare_level")
    public String getWelfareLevel() {
        return this.welfareLevel;
    }

    /**
     * @param welfareLevel
     * 福利级别.
     */
    public void setWelfareLevel(String welfareLevel) {
        this.welfareLevel = welfareLevel;
    }

    /** @return 激活状态. */
    @Column(name = "activation_state")
    public String getActivationState() {
    	return this.activationState;
    }
    
    /**
     * @param activationState
     * 激活状态.
     */
    public void setActivationState(String activationState) {
    	this.activationState = activationState;
    }
    /** @return 所属体系. */
    @Column(name = "system")
    public String getSystem() {
        return this.system;
    }

    /**
     * @param system
     * 所属体系.
     */
    public void setSystem(String system) {
        this.system = system;
    }
    
    /** @return 上属董事. */
    @Column(name = "above_board")
    public String getAboveBoard() {
    	return this.aboveBoard;
    }
    
    /**
     * @param aboveBoard
     * 上属董事.
     */
    public void setAboveBoard(String aboveBoard) {
    	this.aboveBoard = aboveBoard;
    }
    
    /** @return 冻结状态. */
    @Column(name = "frozen_state")
    public String getFrozenState() {
    	return this.frozenState;
    }
    
    /**
     * @param frozenSate
     * 冻结状态.
     */
    public void setFrozenState(String frozenState) {
		this.frozenState = frozenState;
	}
   
    /** @return 所属区域. */
    @Column(name = "area")
    public String getArea() {
    	return this.area;
    }
    
    /**
     * @param area
     * 所属区域.
     */
    public void setArea(String area) {
    	this.area = area;
    }
    /** @return 董事姓名*/
    @Column(name = "director")
    public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}
	
	@Column(name = "director_contact")
	public String getDirectorContact() {
		return directorContact;
	}

	public void setDirectorContact(String directorContact) {
		this.directorContact = directorContact;
	}
	@Column(name = "branch_office")
	public String getBranchOffice() {
		return branchOffice;
	}

	public void setBranchOffice(String branchOffice) {
		this.branchOffice = branchOffice;
	}
	@Column(name = "id_number")
	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}
	
	@Column(name="apply_matter")
	public String getApplyMatter() {
		return applyMatter;
	}

	public void setApplyMatter(String applyMatter) {
		this.applyMatter = applyMatter;
	}
	@Column(name = "apply_content")
	public String getApplyContent() {
		return applyContent;
	}

	public void setApplyContent(String applyContent) {
		this.applyContent = applyContent;
	}
	
	
	@Column(name = "enclosure")
	public String getEnclosure() {
		return enclosure;
	}

	public void setEnclosure(String enclosure) {
		this.enclosure = enclosure;
	}
	@Column( name = "path")
	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	/** @return 申请人. */
    @Column(name = "user_id")
    public Long getUserId() {
        return this.userId;
    }
    /**
     * @param userId
     *            申请人.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    /** @return 流程实例ID. */
    @Column(name = "process_instance_id")
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    /**
     * @param processInstanceId
     *            流程实例ID.
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }

	
    
}
