package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;
/**
 * 发票信息实体类
 */

@Entity
@Table(name = "ENTITY_INVOICE")
public class Invoice implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 身份证号. */
    private String idNumber;

    /** 专卖店编号 */
    private String ucode;

    /** 专卖店名字. */
    private String shopName;

    /** 专卖店电话. */
    private String shopTel;

    /** 发票日期. */
    private Date invoiceDate;

    /** 订单单据号. */
    private String orderNumber;

    /** 所属区域. */
    private String area;
    
    /** 所属体系. */
    private String system;
    
    /** 所属分公司. */
    private String branchOffice;
    
    /** 发票类型. */
    private String invoiceType;
    
    /** 所属类别. */
    private String category;
    
    /** 发票抬头. */
    private String invoiceTitle;
    
    /** 发票明细. */
    private String invoiceDetail;
    
    /** 发票金额. */
    private String invoiceMoney;
    
    /** 企业名称. */
    private String enterpriseName;
    
    /** 税务登记号. */
    private String taxNumber;
    
    /** 开户行. */
    private String openingBank;
    
    /** 开户行账号. */
    private String accountNumber;
    
    /** 企业地址及电话. */
    private String enterpriseAddress;
    
    /** 发票邮寄地址. */
    private String invoiceMailAddress;
    
    /** 收件人姓名. */
    private String addressee;
    
    /** 收件人电话. */
    private String addresseeTel;
    
    /** 收件人备用电话. */
    private String addresseeSpareTel;
    
    /** 上传附件. */
    private String enclosure;
    
    /** 附件路径. */
    private String path;
    
    /** 申请人. */
    private Long userId;
    
    /** 流程实例Id. */
    private String processInstanceId;
    
    public Invoice() {
    }

    public Invoice(Long id) {
        this.id = id;
    }
    
    
    public Invoice(Long id,String idNumber, String ucode,String shopName, String shopTel,Date invoiceDate, String orderNumber,String area,String system,String branchOffice,
    		String invoiceType,String category,String invoiceTitle,String invoiceDetail,String invoiceMoney,String enterpriseName,String taxNumber,String openingBank,
    		String accountNumber,String enterpriseAddress,String invoiceMailAddress,String addressee,String addresseeTel,String addresseeSpareTel,String enclosure,String path,
    		Long userId, String processInstanceId) {
        this.id = id;
        this.idNumber = idNumber;
        this.ucode = ucode;
        this.shopName = shopName;
        this.shopTel = shopTel;
        this.invoiceDate = invoiceDate;
        this.orderNumber = orderNumber;
        this.area = area;
        this.system = system;
        this.branchOffice = branchOffice;
        this.invoiceType = invoiceType;
        this.category = category;
        this.invoiceTitle = invoiceTitle;
        this.invoiceDetail = invoiceDetail;
        this.invoiceMoney = invoiceMoney;
        this.enterpriseName = enterpriseName;
        this.taxNumber = taxNumber;
        this.openingBank = openingBank;
        this.accountNumber = accountNumber;
        this.enterpriseAddress = enterpriseAddress;
        this.invoiceMailAddress = invoiceMailAddress;
        this.addressee = addressee;
        this.addresseeTel = addresseeTel;
        this.addresseeSpareTel = addresseeSpareTel;
        this.enclosure = enclosure;
        this.path = path;
        this.userId = userId;
        this.processInstanceId = processInstanceId;
    }

    /** @return 主键. */
    @Id
    @Column(name = "id")
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name = "id_number")
    public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	/**
     * @param shopId
     *  @return 专卖店编号. */
    @Column(name = "ucode")
    public String getUcode() {
		return ucode;
	}

	public void setUcode(String ucode) {
		this.ucode = ucode;
	}
	/** @return 专卖店名. */
    @Column(name = "shop_name")
	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}
	/** @return 专卖店电话. */
    @Column(name = "shop_tel")
	public String getShopTel() {
		return shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}
	/** @return 发票日期. */
    @Column(name = "invoice_date")
	public Date getInvoiceDate() {
		return invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}
	/** @return 订单单据号. */
    @Column(name = "order_number")
	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}
	/** @return 所属区域. */
    @Column(name = "area")
	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}
	/** @return 所属体系. */
    @Column(name = "system")
	public String getSystem() {
		return system;
	}

	public void setSystem(String system) {
		this.system = system;
	}
	/** @return 所属分公司. */
    @Column(name = "branch_office")
	public String getBranchOffice() {
		return branchOffice;
	}

	public void setBranchOffice(String branchOffice) {
		this.branchOffice = branchOffice;
	}
	/** @return 发票类型. */
    @Column(name = "invoice_type")
	public String getInvoiceType() {
		return invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}
	/** @return 所属类别. */
    @Column(name = "category")
	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}
	/** @return 发票抬头. */
    @Column(name = "invoice_title")
	public String getInvoiceTitle() {
		return invoiceTitle;
	}

	public void setInvoiceTitle(String invoiceTitle) {
		this.invoiceTitle = invoiceTitle;
	}
	/** @return 发票明细. */
    @Column(name = "invoice_detail")
	public String getInvoiceDetail() {
		return invoiceDetail;
	}

	public void setInvoiceDetail(String invoiceDetail) {
		this.invoiceDetail = invoiceDetail;
	}
	/** @return 发票金额. */
    @Column(name = "invoice_money")
	public String getInvoiceMoney() {
		return invoiceMoney;
	}

	public void setInvoiceMoney(String invoiceMoney) {
		this.invoiceMoney = invoiceMoney;
	}
	/** @return 企业名称. */
    @Column(name = "enterprise_name")
	public String getEnterpriseName() {
		return enterpriseName;
	}

	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}
	/** @return 税务登记号. */
    @Column(name = "tax_number")
	public String getTaxNumber() {
		return taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}
	/** @return 开户行. */
    @Column(name = "opening_bank")
	public String getOpeningBank() {
		return openingBank;
	}

	public void setOpeningBank(String openingBank) {
		this.openingBank = openingBank;
	}
	/** @return 开户行账号. */
    @Column(name = "account_number")
	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}
	/** @return 企业地址及电话. */
    @Column(name = "enterprise_address")
	public String getEnterpriseAddress() {
		return enterpriseAddress;
	}

	public void setEnterpriseAddress(String enterpriseAddress) {
		this.enterpriseAddress = enterpriseAddress;
	}
	
	/** @return 发票邮寄地址. */
    @Column(name = "invoice_mail_address")
	public String getInvoiceMailAddress() {
		return invoiceMailAddress;
	}

	public void setInvoiceMailAddress(String invoiceMailAddress) {
		this.invoiceMailAddress = invoiceMailAddress;
	}
	/** @return 收件人姓名. */
    @Column(name = "addressee")
	public String getAddressee() {
		return addressee;
	}

	public void setAddressee(String addressee) {
		this.addressee = addressee;
	}
	/** @return 收件人电话. */
    @Column(name = "addressee_tel")
	public String getAddresseeTel() {
		return addresseeTel;
	}

	public void setAddresseeTel(String addresseeTel) {
		this.addresseeTel = addresseeTel;
	}
	/** @return 收件人备用电话. */
    @Column(name = "addressee_spare_tel")
	public String getAddresseeSpareTel() {
		return addresseeSpareTel;
	}

	public void setAddresseeSpareTel(String addresseeSpareTel) {
		this.addresseeSpareTel = addresseeSpareTel;
	}
	/** @return 上传附件. */
    @Column(name = "enclosure")
	public String getEnclosure() {
		return enclosure;
	}

	public void setEnclosure(String enclosure) {
		this.enclosure = enclosure;
	}

	/**@return 附件路径*/
	@Column(name = "path")
    public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	/** @return 申请人. */
    @Column(name = "user_id")
    public Long getUserId() {
        return this.userId;
    }
    /**
     * @param userId
     *            申请人.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    /** @return 流程实例ID. */
    @Column(name = "process_instance_id")
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    /**
     * @param processInstanceId
     *            流程实例ID.
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }
}
