package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;

import com.mossle.internal.store.persistence.domain.StoreInfo;


public class InvoiceDTO extends CommonDTO implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 身份证号. */
    private String idNumber;

    /** 专卖店编号 */
    private String ucode;

    /** 专卖店名字. */
    private String shopName;

    /** 专卖店电话. */
    private String shopTel;

    /** 发票日期. */
    private String invoiceDate;

    /** 订单单据号. */
    private String orderNumber;

    /** 所属区域. */
    private String area;
    
    /** 所属体系. */
    private String system;
    
    /** 所属分公司. */
    private String branchOffice;
    
    /** 发票类型. */
    private String invoiceType;
    
    /** 所属类别. */
    private String category;
    
    /** 发票抬头. */
    private String invoiceTitle;
    
    /** 发票明细. */
    private String invoiceDetail;
    
    /** 发票金额. */
    private String invoiceMoney;
    
    /** 企业名称. */
    private String enterpriseName;
    
    /** 税务登记号. */
    private String taxNumber;
    
    /** 开户行. */
    private String openingBank;
    
    /** 开户行账号. */
    private String accountNumber;
    
    /** 企业地址及电话. */
    private String enterpriseAddress;
    
  
    /** 发票邮寄地址. */
    private String invoiceMailAddress;
    
    /** 收件人姓名. */
    private String addressee;
    
    /** 收件人电话. */
    private String addresseeTel;
    
    /** 收件人备用电话. */
    private String addresseeSpareTel;
    
    /** 上传附件. */
    private String enclosure;
    
    /** 附件地址. */
    private String path;
   
    /** 申请人. */
    private String userId;
    
    /** 流程实例Id. */
    private String processInstanceId;
    
    /** 受理单编号*/
    private String applyCode;
    
    private List<StoreInfo> storeInfos;
    
    /**用于导出*/
    private Date createTime;
    private Date completeTime;
    /** 批示内容*/
    private String comment;
    public InvoiceDTO() {
    }

    public InvoiceDTO(Long id) {
        this.id = id;
    }

    
    public InvoiceDTO(Long id,String idNumber,String ucode,String shopName, String shopTel,String invoiceDate, String orderNumber,String area,String system,String branchOffice,
    		String invoiceType,String category,String invoiceTitle,String invoiceDetail,String invoiceMoney,String enterpriseName,String taxNumber,String openingBank,
    		String accountNumber,String enterpriseAddress,String invoiceMailAddress,String addressee,String addresseeTel,String addresseeSpareTel,String enclosure,String path,
    		String userId, String processInstanceId) {
    	 this.id = id;
    	 this.idNumber= idNumber;
         this.ucode = ucode;
         this.shopName = shopName;
         this.shopTel = shopTel;
         this.invoiceDate = invoiceDate;
         this.orderNumber = orderNumber;
         this.area = area;
         this.system = system;
         this.branchOffice = branchOffice;
         this.invoiceType = invoiceType;
         this.category = category;
         this.invoiceTitle = invoiceTitle;
         this.invoiceDetail = invoiceDetail;
         this.invoiceMoney = invoiceMoney;
         this.enterpriseName = enterpriseName;
         this.taxNumber = taxNumber;
         this.openingBank = openingBank;
         this.accountNumber = accountNumber;
         this.enterpriseAddress = enterpriseAddress;
         this.invoiceMailAddress = invoiceMailAddress;
         this.addressee = addressee;
         this.addresseeTel = addresseeTel;
         this.addresseeSpareTel = addresseeSpareTel;
         this.enclosure = enclosure;
         this.path = path;
         this.userId = userId;
         this.processInstanceId = processInstanceId;
    }

    /** @return 发票单主键. */
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            发票单主键.
     */
    public void setId(Long id) {
        this.id = id;
    }


   
    
    public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	public String getUcode() {
		return ucode;
	}

	public void setUcode(String ucode) {
		this.ucode = ucode;
	}

	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopTel() {
		return shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	public String getInvoiceDate() {
		return invoiceDate;
	}

	public void setInvoiceDate(String invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getSystem() {
		return system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	public String getArea() {
		return area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getBranchOffice() {
		return branchOffice;
	}

	public void setBranchOffice(String branchOffice) {
		this.branchOffice = branchOffice;
	}

	public String getInvoiceType() {
		return invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getInvoiceTitle() {
		return invoiceTitle;
	}

	public void setInvoiceTitle(String invoiceTitle) {
		this.invoiceTitle = invoiceTitle;
	}

	public String getInvoiceDetail() {
		return invoiceDetail;
	}

	public void setInvoiceDetail(String invoiceDetail) {
		this.invoiceDetail = invoiceDetail;
	}

	public String getInvoiceMoney() {
		return invoiceMoney;
	}

	public void setInvoiceMoney(String invoiceMoney) {
		this.invoiceMoney = invoiceMoney;
	}

	public String getEnterpriseName() {
		return enterpriseName;
	}

	public void setEnterpriseName(String enterpriseName) {
		this.enterpriseName = enterpriseName;
	}

	public String getTaxNumber() {
		return taxNumber;
	}

	public void setTaxNumber(String taxNumber) {
		this.taxNumber = taxNumber;
	}

	public String getOpeningBank() {
		return openingBank;
	}

	public void setOpeningBank(String openingBank) {
		this.openingBank = openingBank;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public String getEnterpriseAddress() {
		return enterpriseAddress;
	}

	public void setEnterpriseAddress(String enterpriseAddress) {
		this.enterpriseAddress = enterpriseAddress;
	}


	public String getInvoiceMailAddress() {
		return invoiceMailAddress;
	}

	public void setInvoiceMailAddress(String invoiceMailAddress) {
		this.invoiceMailAddress = invoiceMailAddress;
	}

	public String getAddressee() {
		return addressee;
	}

	public void setAddressee(String addressee) {
		this.addressee = addressee;
	}

	public String getAddresseeTel() {
		return addresseeTel;
	}

	public void setAddresseeTel(String addresseeTel) {
		this.addresseeTel = addresseeTel;
	}

	public String getAddresseeSpareTel() {
		return addresseeSpareTel;
	}

	public void setAddresseeSpareTel(String addresseeSpareTel) {
		this.addresseeSpareTel = addresseeSpareTel;
	}

	public String getEnclosure() {
		return enclosure;
	}

	public void setEnclosure(String enclosure) {
		this.enclosure = enclosure;
	}
	
	public String getPath(){
		return path;
	}
	public void setPath(String path){
		this.path = path;
	}
	/** @return 申请人. */
    public String getUserId() {
        return this.userId;
    }
    /**
     * @param id
     *            申请人.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    /** @return  */
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }
    
    /**
     * @param 
     *           
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }
    
	public String getApplyCode() {
		return applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	public List<StoreInfo> getStoreInfos() {
		return storeInfos;
	}

	public void setStoreInfos(List<StoreInfo> storeInfos) {
		this.storeInfos = storeInfos;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getCompleteTime() {
		return completeTime;
	}

	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
    
    
}
