package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * 
 * 冻结/解冻实体（违规）
 * @author sjx
 */
@Entity
@Table(name = "ENTITY_LLLEGAL_FREEZE")
public class LllegalFreeze implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 提交次数 */
    private String submitTimes;
    
    /** 单据号*/
    private String applyCode;
    
    /** 主题*/
    private String theme;
    
    /** 抄送*/
    private String cc;
    private String copyUserValue;
    
    /** 申请业务类型*/
    private String businessType;
    
    /** 业务细分*/
    private String businessDetail;
    
    /** 业务级别*/
    private String businessLevel;
    
    /** 发起人*/
    private String initiator;

    /** 编号. */
    private String ucode;

    /** 姓名. */
    private String name;
    
    /** 福利级别. */
    private String welfareLevel;
    
    /** 资格状态*/
    private String qualificationsStatus;
    
    /** 所属体系. */
    private String system;

    /** 联系方式. */
    private String contact;

    /** 所属区域. */
    private String area;
    
    /** 所属分公司. */
    private String company;

    /** 身份证号*/
    private String idNumber;
    
    /** 上属董事. */
    private String aboveBoard;
    
    /** 联系方式（董事）. */
    private String directorContact;
    
    /**申请受理事项*/
    private String applyMatter;
    
    /**申请内容*/
    private String applyContent;
    
    /** 附件名 */
    private String enclosure;
    
    /** 附件路径 */
    private String path;
    
    /** 申请人. */
    private Long userId;
    
    /** 流程实例Id. */
    private String processInstanceId;
    
   
    
    public LllegalFreeze() {
    }

    public LllegalFreeze(Long id) {
        this.id = id;
    }

    
    public LllegalFreeze(Long id,String submitTimes, String applyCode,String theme, String cc,String copyUserValue,String businessType,String businessDetail,String businessLevel,String initiator,
    		String ucode, String name,String welfareLevel,String qualificationsStatus,String system,String contact,String area,String company,
    		String idNumber, String aboveBoard, String directorContact,String applyMatter,String applyContent,String enclosure,String path,
    		Long userId, String processInstanceId) {
        this.id = id;
        this.submitTimes = submitTimes;
        this.applyCode = applyCode;
        this.theme = theme;
        this.cc = cc;
        this.copyUserValue = copyUserValue;
        this.businessType = businessType;
        this.businessDetail = businessDetail;
        this.businessLevel = businessLevel;
        this.initiator = initiator;
        this.ucode = ucode;
        this.name = name;
        this.welfareLevel = welfareLevel;
        this.qualificationsStatus = qualificationsStatus;
        this.system = system;
        this.contact = contact;
        this.area = area;
        this.company = company;
        this.idNumber = idNumber;
        this.aboveBoard = aboveBoard;
        this.directorContact = directorContact;
        this.applyMatter = applyMatter;
        this.applyContent = applyContent;
        this.enclosure = enclosure;
        this.path = path;
        this.userId = userId;
        this.processInstanceId = processInstanceId;
       
    }

    /** @return 主键. */
    @Id
    @Column(name = "id")
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }
    /** 提交次数*/
    @Column(name = "submit_times")
    public String getSubmitTimes(){
    	return this.submitTimes;
    }
    public void setSubmitTimes(String submitTimes){
    	this.submitTimes = submitTimes;
    }
    /**单据号*/
    @Column(name = "apply_code")
    public String getApplyCode() {
		return applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	/** 主题*/
    @Column(name = "theme")
    public String getTheme(){
    	return this.theme;
    }
    public void setTheme(String theme){
    	this.theme = theme;
    }
    /** 抄送*/
    @Column(name = "cc")
    public String getCc(){
    	return this.cc;
    }
    public void setCc(String cc){
    	this.cc = cc;
    }
    @Column(name = "copy_user_value")
    public String getCopyUserValue() {
		return copyUserValue;
	}

	public void setCopyUserValue(String copyUserValue) {
		this.copyUserValue = copyUserValue;
	}

	/** 申请业务类型*/
    @Column(name = "business_type")
    public String getBusinessType(){
    	return this.businessType;
    }
    public void setBusinessType(String businessType){
    	this.businessType = businessType;
    }
   /** 业务细分*/
    @Column(name = "business_detail")
    public String getBusinessDetail() {
		return businessDetail;
	}

	public void setBusinessDetail(String businessDetail) {
		this.businessDetail = businessDetail;
	}
	/** 业务级别*/
	@Column(name = "business_level")
	public String getBusinessLevel() {
		return businessLevel;
	}

	public void setBusinessLevel(String businessLevel) {
		this.businessLevel = businessLevel;
	}

	/** 发起人*/
    @Column(name = "initiator")
    public String getInitiator(){
    	return this.initiator;
    }
    public void setInitiator(String initiator){
    	this.initiator = initiator;
    }

    /** @return 编号. */
    @Column(name = "ucode")
    public String getUcode() {
        return this.ucode;
    }

    /**
     * @param number
     * 编号.
     */
    public void setUcode(String ucode) {
        this.ucode = ucode;
    }
    
    /** @return 姓名. */
    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     * 姓名.
     */
    public void setName(String name) {
        this.name = name;
    }
    /** @return 福利级别. */
    @Column(name = "welfare_level")
    public String getWelfareLevel() {
        return this.welfareLevel;
    }
    public void setWelfareLevel(String welfareLevel){
    	this.welfareLevel = welfareLevel;
    }
    
    /** 资格状态*/
    @Column(name = "qualifications_status")
    public String getQualificationsStatus(){
    	return this.qualificationsStatus;
    }
    public void setQualificationsStatus(String qualificationsStatus){
    	this.qualificationsStatus = qualificationsStatus;
    }
    
    /** @return 所属体系. */
    @Column(name = "system")
    public String getSystem() {
        return this.system;
    }

    /**
     * @param system
     * 所属体系.
     */
    public void setSystem(String system) {
        this.system = system;
    }
    /** @return 联系方式. */
    @Column(name = "contact")
    public String getContact() {
        return this.contact;
    }

    /**
     * @param contact
     * 联系方式.
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /** @return 所属区域. */
    @Column(name = "area")
    public String getArea() {
    	return this.area;
    }
    
    /**
     * @param area
     * 所属区域.
     */
    public void setArea(String area) {
    	this.area = area;
    }

    @Column(name = "branch_office")
	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
   
	@Column(name = "id_number")
	public String getIdNumber() {
		return idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}
    
    /** @return 上属董事. */
    @Column(name = "above_board")
    public String getAboveBoard() {
    	return this.aboveBoard;
    }
    
    /**
     * @param aboveBoard
     * 上属董事.
     */
    public void setAboveBoard(String aboveBoard) {
    	this.aboveBoard = aboveBoard;
    }
  
	@Column(name = "director_contact")
	public String getDirectorContact() {
		return directorContact;
	}

	public void setDirectorContact(String directorContact) {
		this.directorContact = directorContact;
	}
	
	@Column(name="apply_matter")
	public String getApplyMatter() {
		return applyMatter;
	}

	public void setApplyMatter(String applyMatter) {
		this.applyMatter = applyMatter;
	}
	@Column(name = "apply_content")
	public String getApplyContent() {
		return applyContent;
	}

	public void setApplyContent(String applyContent) {
		this.applyContent = applyContent;
	}
	
	
	@Column(name = "enclosure")
	public String getEnclosure() {
		return enclosure;
	}

	public void setEnclosure(String enclosure) {
		this.enclosure = enclosure;
	}
	@Column( name = "path")
	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	/** @return 申请人. */
    @Column(name = "user_id")
    public Long getUserId() {
        return this.userId;
    }
    /**
     * @param userId
     *            申请人.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    /** @return 流程实例ID. */
    @Column(name = "process_instance_id")
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    /**
     * @param processInstanceId
     *            流程实例ID.
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }
   
    
}
