package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * 产品实体类.
 * 
 * @author sjx
 */
@Entity
@Table(name = "ENTITY_PRODUCT")
public class Product implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 产品编号 */
    private String proNo;
    
    /** 产品名称 */
    private String proName;

    /** （店支付）订货数量*/
    private String shopPVNum;
    
    /** (店支付)退货数量. */
    private String shopReNum;

    /** (店支付)总PV. */
    private String shopPV;

    /** (奖励积分)订货数量. */
    private String shopRewardNum;

    /** (奖励积分)退货数量. */
    private String shopRewNum;

    /** (奖励积分)总PV. */
    private String shopRewardPV;

    /** (个人钱包)订货数量. */
    private String shopWalletNum;
    
    /** (个人钱包)退货数量. */
    private String shopwalNum;
    
    /** (个人钱包)总PV. */
    private String shopWalletPV;
    
    /**退货实体表主键*/
    private Long returnId;
    
    /**产品pv值*/
    private String proPV;
    
    public Product() {
    }

    public Product(Long id) {
        this.id = id;
    }

    
    public Product(Long id,String proName,String shopPVNum, String shopReNum, String shopPV,String shopRewardNum,
    		String shopRewNum, String shopRewardPV, String shopWalletNum, String shopwalNum,String shopWalletPV,
    		String processInstanceId) {
        this.id = id;
        this.proName = proName;
        this.shopPVNum = shopPVNum;
        this.shopReNum = shopReNum;
        this.shopPV = shopPV;
        this.shopRewardNum = shopRewardNum;
        this.shopRewNum = shopRewNum;
        this.shopRewardPV = shopRewardPV;
        this.shopWalletNum = shopWalletNum;
        this.shopwalNum = shopwalNum;
        this.shopWalletPV = shopWalletPV;
    }

    /** @return 主键. */
    @Id
    @Column(name = "id")
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * @return
     * 发起存入产品编号，方便调整页面获取编号后用于计算
     */
    @Column(name = "pro_no")
    public String getProNo() {
		return proNo;
	}

	public void setProNo(String proNo) {
		this.proNo = proNo;
	}

	/** 产品名称 */
    @Column(name = "pro_name")
    public String getProName(){
    	return this.proName;
    }
    
    public void setProName(String proName){
    	this.proName = proName;
    }
    /** (店支付）订货数量 */
    @Column( name = "shopPV_num")
    public String getShopPVNum() {
		return shopPVNum;
	}

	public void setShopPVNum(String shopPVNum) {
		this.shopPVNum = shopPVNum;
	}

	 /** (店支付）退货数量 */
	@Column( name = "shopRe_num")
    public String getShopReNum() {
		return shopReNum;
	}

	public void setShopReNum(String shopReNum) {
		this.shopReNum = shopReNum;
	}
	/** (店支付）总PV */
	@Column( name = "shopPV")
	public String getShopPV() {
		return shopPV;
	}

	public void setShopPV(String shopPV) {
		this.shopPV = shopPV;
	}
	/** (奖励积分)订货数量 */
	@Column( name = "shop_reward_num")
	public String getShopRewardNum() {
		return shopRewardNum;
	}

	public void setShopRewardNum(String shopRewardNum) {
		this.shopRewardNum = shopRewardNum;
	}
	/** (奖励积分)退货数量 */
	@Column( name = "shop_rew_num")
	public String getShopRewNum() {
		return shopRewNum;
	}

	public void setShopRewNum(String shopRewNum) {
		this.shopRewNum = shopRewNum;
	}
	/** (奖励积分)总PV */
	@Column( name = "shop_reward_PV")
	public String getShopRewardPV() {
		return shopRewardPV;
	}

	public void setShopRewardPV(String shopRewardPV) {
		this.shopRewardPV = shopRewardPV;
	}
	/** (个人钱包)订货数量 */
	@Column( name = "shop_wallet_num")
	public String getShopWalletNum() {
		return shopWalletNum;
	}

	public void setShopWalletNum(String shopWalletNum) {
		this.shopWalletNum = shopWalletNum;
	}
	/** (个人钱包)退货数量 */
	@Column( name = "shop_wal_num")
	public String getShopwalNum() {
		return shopwalNum;
	}

	public void setShopwalNum(String shopwalNum) {
		this.shopwalNum = shopwalNum;
	}
	/** (个人钱包)总PV */
	@Column( name = "shop_wallet_PV")
	public String getShopWalletPV() {
		return shopWalletPV;
	}

	public void setShopWalletPV(String shopWalletPV) {
		this.shopWalletPV = shopWalletPV;
	}

    /** @return 退货表的主键. */
    @Column(name = "return_id")
	public Long getReturnId() {
		return returnId;
	}

	public void setReturnId(Long returnId) {
		this.returnId = returnId;
	}
	
	/** @return 产品pv值. */
    @Column(name = "pro_pv")
	public String getProPV() {
		return proPV;
	}

	public void setProPV(String proPV) {
		this.proPV = proPV;
	}
    
    
}
