package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * 产品实体类.
 * 
 * @author sjx
 */
public class ProductDTO implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 产品编号 */
    private List<String> proNo;
    
    /** 产品名称 */
    private List<String> proName;

    /** （店支付）订货数量*/
    private List<String> shopPVNum;
    
    /** (店支付)退货数量. */
    private List<String> shopReNum;

    /** (店支付)总PV. */
    private List<String> shopPV;

    /** (奖励积分)订货数量. */
    private List<String> shopRewardNum;

    /** (奖励积分)退货数量. */
    private List<String> shopRewNum;

    /** (奖励积分)总PV. */
    private List<String> shopRewardPV;

    /** (个人钱包)订货数量. */
    private List<String> shopWalletNum;
    
    /** (个人钱包)退货数量. */
    private List<String> shopwalNum;
    
    /** (个人钱包)总PV. */
    private List<String> shopWalletPV;
    
    /**退货实体表主键*/
    private Long returnId;
    
    /**产品pv值*/
    private List<String> proPV;
    
    public ProductDTO() {
    }

    public ProductDTO(Long id) {
        this.id = id;
    }

    
    public ProductDTO(Long id,List<String> proName,List<String> shopPVNum, List<String> shopReNum, List<String> shopPV,List<String> shopRewardNum,
    		List<String> shopRewNum, List<String> shopRewardPV, List<String> shopWalletNum, List<String> shopwalNum,List<String> shopWalletPV,List<String> proPV
    		) {
        this.id = id;
        this.proName = proName;
        this.shopPVNum = shopPVNum;
        this.shopReNum = shopReNum;
        this.shopPV = shopPV;
        this.shopRewardNum = shopRewardNum;
        this.shopRewNum = shopRewNum;
        this.shopRewardPV = shopRewardPV;
        this.shopWalletNum = shopWalletNum;
        this.shopwalNum = shopwalNum;
        this.shopWalletPV = shopWalletPV;
        this.proPV = proPV;
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public List<String> getProNo() {
		return proNo;
	}

	public void setProNo(List<String> proNo) {
		this.proNo = proNo;
	}

	public List<String> getProName() {
		return proName;
	}

	public void setProName(List<String> proName) {
		this.proName = proName;
	}

	public List<String> getShopPVNum() {
		return shopPVNum;
	}

	public void setShopPVNum(List<String> shopPVNum) {
		this.shopPVNum = shopPVNum;
	}

	public List<String> getShopReNum() {
		return shopReNum;
	}

	public void setShopReNum(List<String> shopReNum) {
		this.shopReNum = shopReNum;
	}

	public List<String> getShopPV() {
		return shopPV;
	}

	public void setShopPV(List<String> shopPV) {
		this.shopPV = shopPV;
	}

	public List<String> getShopRewardNum() {
		return shopRewardNum;
	}

	public void setShopRewardNum(List<String> shopRewardNum) {
		this.shopRewardNum = shopRewardNum;
	}

	public List<String> getShopRewNum() {
		return shopRewNum;
	}

	public void setShopRewNum(List<String> shopRewNum) {
		this.shopRewNum = shopRewNum;
	}

	public List<String> getShopRewardPV() {
		return shopRewardPV;
	}

	public void setShopRewardPV(List<String> shopRewardPV) {
		this.shopRewardPV = shopRewardPV;
	}

	public List<String> getShopWalletNum() {
		return shopWalletNum;
	}

	public void setShopWalletNum(List<String> shopWalletNum) {
		this.shopWalletNum = shopWalletNum;
	}

	public List<String> getShopwalNum() {
		return shopwalNum;
	}

	public void setShopwalNum(List<String> shopwalNum) {
		this.shopwalNum = shopwalNum;
	}

	public List<String> getShopWalletPV() {
		return shopWalletPV;
	}

	public void setShopWalletPV(List<String> shopWalletPV) {
		this.shopWalletPV = shopWalletPV;
	}

	public Long getReturnId() {
		return returnId;
	}

	public void setReturnId(Long returnId) {
		this.returnId = returnId;
	}

	public List<String> getProPV() {
		return proPV;
	}

	public void setProPV(List<String> proPV) {
		this.proPV = proPV;
	}

    
}
