package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


public class ReturnDTO extends CommonDTO implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;
    
    /** 仓库地址 */
    private String wareHouse;
    
    /** 客服工号 */
    private String empNo;

    /** 专卖店编号. */
    private String ucode;

    /** 专卖店姓名. */
    private String shopName;

    /** 专卖店电话. */
    private String shopTel;

    /** 申请退货日期. */
    private String returnDate;

    /** 订单单据号. */
    private String orderNumber;

    /** 退货原因. */
    private String returnReaon;
    
    /** 店支付库存. */
    private String shopPayStock;
    
    /** 奖励积分库存. */
    private String rewardIntegralStock;
    
    /** 个人钱包库存. */
    private String personPayStock;
    
    /** 店钱包50元. */
    private String payType;
    
    /** 申请人. */
    private Long userId;
    
    /** 流程实例Id. */
    private String processInstanceId;
    
    /** 受理单编号*/
    private String applyCode;
    
    /** 提交次数 */
    private String submitTimes;
    /**用于导出*/
    private Date createTime;
    private Date completeTime;
    /** 批示内容*/
    private String comment;
    /** 减免受理单号*/
    private String inputApplyCode;
    /** 开户行*/
    private String bankDeposit;
    /** 开户名*/
    private String accountName;
    /** 开户账号*/
    private String accountNumber;
    
    
    
    
    public String getInputApplyCode() {
		return inputApplyCode;
	}

	public void setInputApplyCode(String inputApplyCode) {
		this.inputApplyCode = inputApplyCode;
	}

	public String getBankDeposit() {
		return bankDeposit;
	}

	public void setBankDeposit(String bankDeposit) {
		this.bankDeposit = bankDeposit;
	}

	public String getAccountName() {
		return accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getAccountNumber() {
		return accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	public ReturnDTO() {
    }

    public ReturnDTO(Long id) {
        this.id = id;
    }

    
    public ReturnDTO(Long id, String empNo,String wareHouse, String ucode, String shopName,String payType,
    		String returnDate, String shopTel, String orderNumber, String returnReaon,String shopPayStock,String rewardIntegralStock,String personPayStock,
    		Long userId, String processInstanceId) {
    	 this.id = id;
    	 this.empNo = empNo;
    	 this.wareHouse = wareHouse;
         this.ucode = ucode;
         this.shopName = shopName;
         this.returnDate = returnDate;
         this.shopTel = shopTel;
         this.orderNumber = orderNumber;
         this.returnReaon = returnReaon;
         this.shopPayStock = shopPayStock;
         this.rewardIntegralStock = rewardIntegralStock;
         this.personPayStock = personPayStock;
         this.payType = payType;
         this.userId = userId;
         this.processInstanceId = processInstanceId;
    }
    
	public String getSubmitTimes() {
		return submitTimes;
	}

	public void setSubmitTimes(String submitTimes) {
		this.submitTimes = submitTimes;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	

	public String getWareHouse() {
		return wareHouse;
	}

	public void setWareHouse(String wareHouse) {
		this.wareHouse = wareHouse;
	}
	
	public String getEmpNo() {
		return empNo;
	}

	public void setEmpNo(String empNo) {
		this.empNo = empNo;
	}

	public String getUcode() {
		return ucode;
	}

	public void setUcode(String ucode) {
		this.ucode = ucode;
	}

	public String getShopName() {
		return shopName;
	}

	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	public String getShopTel() {
		return shopTel;
	}

	public void setShopTel(String shopTel) {
		this.shopTel = shopTel;
	}

	public String getReturnDate() {
		return returnDate;
	}

	public void setReturnDate(String returnDate) {
		this.returnDate = returnDate;
	}

	public String getOrderNumber() {
		return orderNumber;
	}

	public void setOrderNumber(String orderNumber) {
		this.orderNumber = orderNumber;
	}

	public String getReturnReaon() {
		return returnReaon;
	}

	public void setReturnReaon(String returnReaon) {
		this.returnReaon = returnReaon;
	}

	public String getShopPayStock() {
		return shopPayStock;
	}

	public void setShopPayStock(String shopPayStock) {
		this.shopPayStock = shopPayStock;
	}

	public String getRewardIntegralStock() {
		return rewardIntegralStock;
	}

	public void setRewardIntegralStock(String rewardIntegralStock) {
		this.rewardIntegralStock = rewardIntegralStock;
	}

	public String getPersonPayStock() {
		return personPayStock;
	}

	public void setPersonPayStock(String personPayStock) {
		this.personPayStock = personPayStock;
	}

	public String getPayType() {
		return payType;
	}

	public void setPayType(String payType) {
		this.payType = payType;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getProcessInstanceId() {
		return processInstanceId;
	}

	public void setProcessInstanceId(String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public String getApplyCode() {
		return applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getCompleteTime() {
		return completeTime;
	}

	public void setCompleteTime(Date completeTime) {
		this.completeTime = completeTime;
	}

	public String getComment() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}
	
    
}
