package com.mossle.operation.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TestEntity 测试实体.
 * 
 * @author zyl
 */
@Entity
@Table(name = "TEST_ENTITY")
public class TestEntity implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 请假原因. */
    private String reason;

    /** 请假类型. */
    private String type;

    /** 开始日期. */
    private Date startDate;

    /** 开始时间. */
    private String startDateTime;

    /** 结束日期. */
    private Date endDate;

    /** 结束时间. */
    private String endDateTime;
    
    /** 申请人. */
    private Long userId;
    
    /** 流程实例Id. */
    private String processInstanceId;
    
    public TestEntity() {
    }

    public TestEntity(Long id) {
        this.id = id;
    }

    
    public TestEntity(Long id, String reason, String type,
    		Date startDate, String startDateTime, Date endDate, String endDateTime,
    		Long userId, String processInstanceId) {
        this.id = id;
        this.reason = reason;
        this.type = type;
        this.startDate = startDate;
        this.startDateTime = startDateTime;
        this.endDate = endDate;
        this.endDateTime = endDateTime;
        this.userId = userId;
        this.processInstanceId = processInstanceId;
    }

    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }
    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }


    /** @return 请假原因. */
    @Column(name = "REASON", length = 100)
    public String getReason() {
        return this.reason;
    }

    /**
     * @param reason
     *            请假原因.
     */
    public void setReason(String reason) {
        this.reason = reason;
    }
    
    /** @return 请假类型. */
    @Column(name = "TYPE_NAME")
    public String getType() {
        return this.type;
    }

    /**
     * @param type
     *            请假类型.
     */
    public void setType(String type) {
        this.type = type;
    }
    
    /** @return 开始日期. */
    @Column(name = "START_DATE")
    public Date getStartDate() {
        return this.startDate;
    }

    /**
     * @param startDate
     *            开始日期.
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /** @return 开始时间. */
    @Column(name = "START_DATETIME", length = 50)
    public String getStartDateTime() {
        return this.startDateTime;
    }

    /**
     * @param startDateTime
     *            开始时间.
     */
    public void setStartDateTime(String startDateTime) {
        this.startDateTime = startDateTime;
    }

    /** @return 结束日期. */
    @Column(name = "END_DATE")
    public Date getEndDate() {
        return this.endDate;
    }

    /**
     * @param endDate
     *            结束日期.
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /** @return 结束时间. */
    @Column(name = "END_DATETIME", length = 50)
    public String getEndDateTime() {
        return this.startDateTime;
    }

    /**
     * @param endDateTime
     *            结束时间.
     */
    public void setEndDateTime(String endDateTime) {
        this.endDateTime = endDateTime;
    }
    
    /** @return 申请人. */
    @Column(name = "USER_ID")
    public Long getUserId() {
        return this.userId;
    }
    /**
     * @param id
     *            申请人.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    
    /** @return 结束时间. */
    @Column(name = "PROCESS_INSTANCEID", length = 200)
    public String getProcessInstanceId() {
        return this.processInstanceId;
    }

    /**
     * @param endDateTime
     *            结束时间.
     */
    public void setProcessInstanceId(String processInstanceId) {
        this.processInstanceId = processInstanceId;
    }
}
