package com.mossle.humantask.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskInfoApprovePosition 流程与岗位关系表.
 * 
 * @author zyl
 */
@Entity
@Table(name = "TASK_INFO_APPROVE_POSITION")
public class TaskInfoApprovePosition implements java.io.Serializable {
	
    private static final long serialVersionUID = 0L;

    /** task_info 表主键*/
    private Long taskId;

    /** 岗位及人员ID */
    private Long positionId;

    /** 类型  1：岗位  2：人员 */
    private String positionType;

    /** 业务编号 */
    private String businessKey;
    
    /** （人员/岗位）的上级机构ID **/
    private Long positionParentId;
    
    /** 新旧数据 1:新，2：旧 **/
    private String dataType;
    
    /** 审批节点的人员/岗位信息 **/
    private String approvePositionName;

    public TaskInfoApprovePosition() {
    }

   
    /** @return 主键. */
    @Id
    @Column(name = "TASK_ID", unique = true, nullable = false)
    public Long getTaskId() {
        return this.taskId;
    }

    /**
     * @param id
     *            主键.
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }
    
   
    /** @return 业务标识. */
    @Column(name = "BUSINESS_KEY", length = 100)
    public String getBusinessKey() {
        return this.businessKey;
    }

    /**
     * @param businessKey
     *            业务标识.
     */
    public void setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }

    /** @return 岗位及人员ID. */
    @Column(name = "POSITION_ID", length = 100)
    public Long getPositionId() {
        return this.positionId;
    }

    /**
     * @param positionId
     *            岗位及人员ID.
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /** @return 类型. */
    @Column(name = "POSITION_TYPE", length = 200)
    public String getPositionType() {
        return this.positionType;
    }

    /**
     * @param name
     *            类型.
     */
    public void setPositionType(String positionType) {
        this.positionType = positionType;
    }

    /**
     * @return （人员/岗位）的上级机构ID
     * **/
    @Column(name = "position_parentId", length = 100)
	public Long getPositionParentId() {
		return positionParentId;
	}
    
    /**
     * @param （人员/岗位）的上级机构ID
     * **/
	public void setPositionParentId(Long positionParentId) {
		this.positionParentId = positionParentId;
	}

	/**
     * @return 新旧数据 1:新，2：旧
     * **/
	@Column(name = "data_type", length = 2)
	public String getDataType() {
		return dataType;
	}

	/**
     * @param 新旧数据 1:新，2：旧
     * **/
	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	/**
     * @return 审批节点的人员/岗位信息
     * **/
	@Column(name = "approve_position_name", length = 128)
	public String getApprovePositionName() {
		return approvePositionName;
	}

	/**
     * @param 审批节点的人员/岗位信息
     * **/
	public void setApprovePositionName(String approvePositionName) {
		this.approvePositionName = approvePositionName;
	}
    
    
}
