package com.mossle.humantask.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskInfo 人工任务列表展示项.
 * 
 * @author sjx
 */

public class TaskInfoAndRecord implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    private Long id;
    /** 任务名称. */
    private String name;

    /** 状态. */
    private String status;

    /** 展示标题. */
    private String presentationSubject;

    /** 创建时间. */
    private Date createTime;

    /** 完成时间. */
    private Date completeTime;


    /** 负责人. */
    private String assignee;

    /** 关联的流程发起人. */
    private String processStarter;

    /** 分类. */
    private String catalog;

    /** 操作. */
    private String action;
    
    /** 受理单据号 */
    private String applyCode;
    /** 大区id */
    private String areaId;
    /** 大区名称 */
    private String areaName;
    /** 分公司id */
    private String companyId;
    /** 分公司名称 */
    private String companyName;
    /** 业务类型id */
    private String businessTypeId;
    /** 业务类型名称 */
    private String businessTypeName;
    /** 业务细分id */
    private String businessdDetailId;
    /** 业务细分名称 */
    private String businessDetailName;
    /** 流程状态 */
    private String auditStatus;
    /** 流程配置key */
    private String businessKey;
    
    
    public void TaskAndRecord(){
    	
    }
    public void TaskAndRecord(Long id){
    	this.id = id;
    }

    /** @return 任务名称. */
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            任务名称.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return 状态. */
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            状态.
     */
    public void setStatus(String status) {
        this.status = status;
    }

   

    /** @return 展示标题. */
    public String getPresentationSubject() {
        return this.presentationSubject;
    }

    /**
     * @param presentationSubject
     *            展示标题.
     */
    public void setPresentationSubject(String presentationSubject) {
        this.presentationSubject = presentationSubject;
    }

    /** @return 创建时间. */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            创建时间.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return 完成时间. */
    public Date getCompleteTime() {
        return this.completeTime;
    }

    /**
     * @param completeTime
     *            完成时间.
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /** @return 负责人. */
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            负责人.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    /** @return 关联的流程发起人. */
    public String getProcessStarter() {
        return this.processStarter;
    }

    /**
     * @param processStarter
     *            关联的流程发起人.
     */
    public void setProcessStarter(String processStarter) {
        this.processStarter = processStarter;
    }

    /** @return 分类. */
    public String getCatalog() {
        return this.catalog;
    }

    /**
     * @param catalog
     *            分类.
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog;
    }

    /** @return 操作. */
    public String getAction() {
        return this.action;
    }

    /**
     * @param action
     *            操作.
     */
    public void setAction(String action) {
        this.action = action;
    }

	public String getApplyCode() {
		return applyCode;
	}

	public void setApplyCode(String applyCode) {
		this.applyCode = applyCode;
	}
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public String getAreaId() {
		return areaId;
	}
	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}
	public String getAreaName() {
		return areaName;
	}
	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}
	public String getCompanyId() {
		return companyId;
	}
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}
	public String getCompanyName() {
		return companyName;
	}
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}
	public String getBusinessTypeId() {
		return businessTypeId;
	}
	public void setBusinessTypeId(String businessTypeId) {
		this.businessTypeId = businessTypeId;
	}
	public String getBusinessTypeName() {
		return businessTypeName;
	}
	public void setBusinessTypeName(String businessTypeName) {
		this.businessTypeName = businessTypeName;
	}
	
	public String getBusinessdDetailId() {
		return businessdDetailId;
	}
	public void setBusinessdDetailId(String businessdDetailId) {
		this.businessdDetailId = businessdDetailId;
	}
	public String getBusinessDetailName() {
		return businessDetailName;
	}
	public void setBusinessDetailName(String businessDetailName) {
		this.businessDetailName = businessDetailName;
	}
	public String getAuditStatus() {
		return auditStatus;
	}
	public void setAuditStatus(String auditStatus) {
		this.auditStatus = auditStatus;
	}
	public String getBusinessKey() {
		return businessKey;
	}
	public void setBusinessKey(String businessKey) {
		this.businessKey = businessKey;
	}
    
}
