package com.mossle.auth.persistence.domain;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 *考勤组
 * 
 * @author cz 20180726
 */
@Entity
@Table(name = "attendance_records")
public class AttendanceRecords implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 考勤组名称. */
    private String recordName;

    /** 班次类型id. */
    private String typeID;

    /** 周一班次id. */
    private String mondayShiftID;

    /** 周二班次id. */
    private String tuesdayShiftID;

    /** 周三班次id. */
    private String wednesdayShiftID;

    /** 周四班次id. */
    private String thursdayShiftID;
    
    /** 周五班次id. */
    private String fridayShiftID;
    
    /**周六班次id*/
    private String SaturdayShiftID;

    /**周日班次id*/
    private String SundayShiftID;
    
    /**备注*/
    private String note;
    


    public AttendanceRecords() {
    }

    public AttendanceRecords(Long id) {
        this.id = id;
    }

    
 
    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    
    /** 考勤组名称. */
    @Column(name = "recordName" )
    public String getRecordName() {
		return recordName;
	}

	public void setRecordName(String recordName) {
		this.recordName = recordName;
	}

	
	/** 班次类型id. */
	@Column(name = "typeID")
	public String getTypeID() {
		return typeID;
	}

	public void setTypeID(String typeID) {
		this.typeID = typeID;
	}

	/** 周一班次id. */
	@Column(name = "mondayShiftID")
	public String getMondayShiftID() {
		return mondayShiftID;
	}

	public void setMondayShiftID(String mondayShiftID) {
		this.mondayShiftID = mondayShiftID;
	}

	
	@Column(name = "tuesdayShiftID")
	public String getTuesdayShiftID() {
		return tuesdayShiftID;
	}

	public void setTuesdayShiftID(String tuesdayShiftID) {
		this.tuesdayShiftID = tuesdayShiftID;
	}

	
	@Column(name = "wednesdayShiftID")
	public String getWednesdayShiftID() {
		return wednesdayShiftID;
	}

	public void setWednesdayShiftID(String wednesdayShiftID) {
		this.wednesdayShiftID = wednesdayShiftID;
	}

	
	@Column(name = "thursdayShiftID")
	public String getThursdayShiftID() {
		return thursdayShiftID;
	}

	public void setThursdayShiftID(String thursdayShiftID) {
		this.thursdayShiftID = thursdayShiftID;
	}

	
	@Column(name = "fridayShiftID")
	public String getFridayShiftID() {
		return fridayShiftID;
	}

	public void setFridayShiftID(String fridayShiftID) {
		this.fridayShiftID = fridayShiftID;
	}

	
	@Column(name = "SaturdayShiftID")
	public String getSaturdayShiftID() {
		return SaturdayShiftID;
	}

	public void setSaturdayShiftID(String saturdayShiftID) {
		SaturdayShiftID = saturdayShiftID;
	}

	
	@Column(name = "SundayShiftID")
	public String getSundayShiftID() {
		return SundayShiftID;
	}

	public void setSundayShiftID(String sundayShiftID) {
		SundayShiftID = sundayShiftID;
	}

	
	@Column(name = "note")
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

    
}
