package com.mossle.auth.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 *考勤组
 * 
 * @author cz 20180726
 */

public class AttendanceImportSetDTO implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 导入截至日期. */
    private String cutOffData;

    /** 起始时间. */
    private Date startData;

    /** 结束时间. */
    private Date endData;

    /** 备注. */
    private String note;


    public AttendanceImportSetDTO() {
    }

    public AttendanceImportSetDTO(Long id) {
        this.id = id;
    }

    
    /** @return 主键. */
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }
	
    
	/** 导入截至日期. */
  
	public String getCutOffData() {
		return cutOffData;
	}

	public void setCutOffData(String cutOffData) {
		this.cutOffData = cutOffData;
	}

	
	/** 起始时间. */
 
	public Date getStartData() {
		return startData;
	}

	public void setStartData(Date startData) {
		this.startData = startData;
	}

	
	/** 结束时间. */
 
	public Date getEndData() {
		return endData;
	}

	public void setEndData(Date endData) {
		this.endData = endData;
	}

	
	/** 备注. */
 
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

    
}
