package com.mossle.auth.persistence.domain;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 *人员和考勤组关联表
 * 
 * @author cz 20180726
 */

public class PersonAttendanceRecordsDTO implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 员工所属考勤组ID. */
    private Long attendanceRecordsID;

    /** 员工ID. */
    private Long personID;
    
    /** 员工姓名. */
    private String personName;


    public PersonAttendanceRecordsDTO() {
    }

    public PersonAttendanceRecordsDTO(Long id) {
        this.id = id;
    }

    /** @return 主键. */
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 员工所属考勤组ID. */
    public Long getAttendanceRecordsID() {
		return attendanceRecordsID;
	}

	public void setAttendanceRecordsID(Long attendanceRecordsID) {
		this.attendanceRecordsID = attendanceRecordsID;
	}

	 /** @return 员工ID. */
	public Long getPersonID() {
		return personID;
	}

	public void setPersonID(Long personID) {
		this.personID = personID;
	}
 
	 /** @return 员工姓名. */
   public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}
	
}
