package com.mossle.auth.persistence.domain;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 *人员和考勤组关联表
 * 
 * @author cz 20180726
 */
@Entity
@Table(name = "person_attendance_records")
public class PersonAttendanceRecords implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 员工所属考勤组ID. */
    private Long attendanceRecordsID;

    /** 员工ID. */
    private Long personID;
    
    /** 员工姓名. */
    private String personName;


    public PersonAttendanceRecords() {
    }

    public PersonAttendanceRecords(Long id) {
        this.id = id;
    }

    
 
    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 员工所属考勤组ID. */
    @Column(name = "attendanceRecordsID")
    public Long getAttendanceRecordsID() {
		return attendanceRecordsID;
	}

	public void setAttendanceRecordsID(Long attendanceRecordsID) {
		this.attendanceRecordsID = attendanceRecordsID;
	}

	 /** @return 员工ID. */
    @Column(name = "personID")
	public Long getPersonID() {
		return personID;
	}

	public void setPersonID(Long personID) {
		this.personID = personID;
	}

	
	 /** @return 员工姓名. */
    @Column(name = "personName")
	public String getPersonName() {
		return personName;
	}

	public void setPersonName(String personName) {
		this.personName = personName;
	}
	
	
 
}
