package com.mossle.auth.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import org.activiti.engine.impl.bpmn.data.Data;

/**
 *考勤组
 * 
 * @author cz 20180726
 */
@Entity
@Table(name = "special_date")
public class SpecialDate implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** 考勤组ID. */
    private Long attendanceRecordID;

    /** 班次id. */
    private String shiftID;

    /** 特殊日期. */
    private Date specialDate;



    public SpecialDate() {
    }

    public SpecialDate(Long id) {
        this.id = id;
    }

    
 
    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    
    
    /** @return 考勤组ID. */
  
    @Column(name = "attendanceRecordID" )
   public Long getAttendanceRecordID() {
		return attendanceRecordID;
	}

	public void setAttendanceRecordID(Long attendanceRecordID) {
		this.attendanceRecordID = attendanceRecordID;
	}

	/**  班次id. */
 
    @Column(name = "shiftID" )
	public String getShiftID() {
		return shiftID;
	}

	public void setShiftID(String shiftID) {
		this.shiftID = shiftID;
	}

	
	/** 特殊日期. */
    @Column(name = "specialDate" )
	public Date getSpecialDate() {
		return specialDate;
	}

	public void setSpecialDate(Date specialDate) {
		this.specialDate = specialDate;
	}

    
}
