package com.mossle.audit.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditBase .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "AUDIT_BASE")
public class AuditBase implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String userId;

    /** null. */
    private String resourceType;

    /** null. */
    private String resourceId;

    /** null. */
    private String action;

    /** null. */
    private String result;

    /** null. */
    private String application;

    /** null. */
    private Date auditTime;

    /** null. */
    private String client;

    /** null. */
    private String server;

    /** null. */
    private String description;

    /** null. */
    private String tenantId;

    private String type; 		// 日志类型（1：接入日志；2：错误日志）
	private String title;		// 日志标题
	private String requestUri; 	// 操作的URI
	private String method; 		// 操作的方式
	private String params; 		// 操作提交的数据
	private String userAgent;	// 操作用户代理信息
	private String exception; 	// 异常信息
	
    public AuditBase() {
    }

    public AuditBase(Long id) {
        this.id = id;
    }

    public AuditBase(Long id, String userId, String resourceType,
            String resourceId, String action, String result,
            String application, Date auditTime, String client, String server,
            String description, String tenantId) {
        this.id = id;
        this.userId = userId;
        this.resourceType = resourceType;
        this.resourceId = resourceId;
        this.action = action;
        this.result = result;
        this.application = application;
        this.auditTime = auditTime;
        this.client = client;
        this.server = server;
        this.description = description;
        this.tenantId = tenantId;
    }

    /** @return null. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "USER_ID", length = 200)
    public String getUserId() {
        return this.userId;
    }

    /**
     * @param userId
     *            null.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** @return null. */
    @Column(name = "RESOURCE_TYPE", length = 200)
    public String getResourceType() {
        return this.resourceType;
    }

    /**
     * @param resourceType
     *            null.
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    /** @return null. */
    @Column(name = "RESOURCE_ID", length = 200)
    public String getResourceId() {
        return this.resourceId;
    }

    /**
     * @param resourceId
     *            null.
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /** @return null. */
    @Column(name = "ACTION", length = 200)
    public String getAction() {
        return this.action;
    }

    /**
     * @param action
     *            null.
     */
    public void setAction(String action) {
        this.action = action;
    }

    /** @return null. */
    @Column(name = "RESULT", length = 200)
    public String getResult() {
        return this.result;
    }

    /**
     * @param result
     *            null.
     */
    public void setResult(String result) {
        this.result = result;
    }

    /** @return null. */
    @Column(name = "APPLICATION", length = 200)
    public String getApplication() {
        return this.application;
    }

    /**
     * @param application
     *            null.
     */
    public void setApplication(String application) {
        this.application = application;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "AUDIT_TIME", length = 26)
    public Date getAuditTime() {
        return this.auditTime;
    }

    /**
     * @param auditTime
     *            null.
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /** @return null. */
    @Column(name = "CLIENT", length = 200)
    public String getClient() {
        return this.client;
    }

    /**
     * @param client
     *            null.
     */
    public void setClient(String client) {
        this.client = client;
    }

    /** @return null. */
    @Column(name = "SERVER", length = 200)
    public String getServer() {
        return this.server;
    }

    /**
     * @param server
     *            null.
     */
    public void setServer(String server) {
        this.server = server;
    }

    /** @return null. */
    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     *            null.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** @return null. */
    @Column(name = "TENANT_ID", length = 64)
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * @param tenantId
     *            null.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }

    @Column(name = "LOG_TYPE", length = 64)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	@Column(name = "LOG_TITLE", length = 200)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "REQUEST_URI", length = 200)
	public String getRequestUri() {
		return requestUri;
	}

	public void setRequestUri(String requestUri) {
		this.requestUri = requestUri;
	}

	@Column(name = "METHOD", length = 200)
	public String getMethod() {
		return method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "PARAMS", length = 200)
	public String getParams() {
		return params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "USER_AGENT", length = 200)
	public String getUserAgent() {
		return userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}

	@Column(name = "LOG_EXCEPTION", length = 4000)
	public String getException() {
		return exception;
	}

	public void setException(String exception) {
		this.exception = exception;
	}
}
